// ============================================================
// Database Types — Auto-generated by Supabase
// Regenerate with: npx supabase gen types typescript --project-id <ref> > src/types/database.types.ts
// ============================================================
// This file is a placeholder. Run the generation command above
// after your migrations are applied to get full type safety.
// ============================================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string
          email: string
          phone: string | null
          department_id: string | null
          employee_student_id: string | null
          avatar_url: string | null
          is_approved: boolean
          is_active: boolean
          approved_by: string | null
          approved_at: string | null
          rejection_reason: string | null
          last_seen_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name: string
          email: string
          phone?: string | null
          department_id?: string | null
          employee_student_id?: string | null
          avatar_url?: string | null
          is_approved?: boolean
          is_active?: boolean
        }
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      roles: {
        Row: {
          id: string
          name: string
          display_name: string
          description: string | null
          permissions: Json
          is_system: boolean
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          name: string
          display_name: string
          description?: string | null
          permissions?: Json
          is_system?: boolean
          is_active?: boolean
        }
        Update: Partial<Database['public']['Tables']['roles']['Insert']>
      }
      departments: {
        Row: {
          id: string
          name: string
          code: string | null
          head_id: string | null
          description: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          name: string
          code?: string | null
          head_id?: string | null
          description?: string | null
          is_active?: boolean
        }
        Update: Partial<Database['public']['Tables']['departments']['Insert']>
      }
      buildings: {
        Row: {
          id: string
          name: string
          code: string | null
          description: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: { name: string; code?: string | null; description?: string | null }
        Update: Partial<Database['public']['Tables']['buildings']['Insert']>
      }
      maintenance_requests: {
        Row: {
          id: string
          request_number: string
          requester_id: string
          category_id: string | null
          building_id: string | null
          room_id: string | null
          location_detail: string | null
          title: string
          description: string
          priority_level: 'Low' | 'Medium' | 'High' | 'Urgent'
          status: string
          hod_id: string | null
          assigned_to: string | null
          assigned_by: string | null
          rejection_reason: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          requester_id: string
          title: string
          description: string
          priority_level?: 'Low' | 'Medium' | 'High' | 'Urgent'
          category_id?: string | null
          building_id?: string | null
          room_id?: string | null
          location_detail?: string | null
        }
        Update: Partial<Database['public']['Tables']['maintenance_requests']['Insert']> & {
          status?: string
          assigned_to?: string | null
          rejection_reason?: string | null
        }
      }
      inventory_items: {
        Row: {
          id: string
          item_code: string
          name: string
          description: string | null
          category_id: string | null
          serial_number: string | null
          model: string | null
          manufacturer: string | null
          acquisition_date: string | null
          acquisition_cost: number | null
          funding_source: string | null
          condition: 'New' | 'Good' | 'Fair' | 'Poor' | 'For_Disposal'
          building_id: string | null
          room_id: string | null
          is_borrowable: boolean
          quantity: number
          available_quantity: number
          image_url: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          name: string
          category_id?: string | null
          serial_number?: string | null
          condition?: 'New' | 'Good' | 'Fair' | 'Poor' | 'For_Disposal'
          quantity?: number
          available_quantity?: number
          is_borrowable?: boolean
        }
        Update: Partial<Database['public']['Tables']['inventory_items']['Insert']>
      }
      equipment_loans: {
        Row: {
          id: string
          loan_number: string
          item_id: string
          borrower_id: string
          loan_type: 'reservation' | 'walk_in'
          quantity_borrowed: number
          purpose: string
          expected_return_date: string
          status: string
          created_at: string
          updated_at: string
        }
        Insert: {
          item_id: string
          borrower_id: string
          loan_type?: 'reservation' | 'walk_in'
          quantity_borrowed?: number
          purpose: string
          expected_return_date: string
        }
        Update: Partial<Database['public']['Tables']['equipment_loans']['Insert']> & {
          status?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          title: string
          body: string
          type: string
          reference_type: string | null
          reference_id: string | null
          is_read: boolean
          read_at: string | null
          action_url: string | null
          created_at: string
        }
        Insert: {
          user_id: string
          title: string
          body: string
          type?: string
          reference_type?: string | null
          reference_id?: string | null
        }
        Update: { is_read?: boolean; read_at?: string | null }
      }
    }
    Views: Record<string, never>
    Functions: {
      has_role: {
        Args: { role_name: string }
        Returns: boolean
      }
      has_any_role: {
        Args: { role_names: string[] }
        Returns: boolean
      }
    }
    Enums: Record<string, never>
  }
}
